laravel/app/routes.php
<?php

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('/home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('empresa', array('as' => 'quemsomos', 'uses' => 'QuemsomosController@index'));
Route::get('empresa/quemsomos', array('as' => 'quemsomos', 'uses' => 'QuemsomosController@index'));
Route::get('politica-de-privacidade', array('as' => 'privacidade', 'uses' => 'PrivacidadeController@index'));
Route::get('empresa/diferenciais', array('as' => 'diferenciais', 'uses' => 'DiferenciaisController@index'));
Route::get('solucoes/{slug?}', array('as' => 'solucoes', 'uses' => 'SolucoesController@index'));
// Route::get('oportunidades', array('as' => 'oportunidades', 'uses' => 'OportunidadesController@index'));
// Route::get('oportunidades/detalhe/{slug?}', array('as' => 'oportunidades', 'uses' => 'OportunidadesController@detalhe'));
// Route::post('oportunidades/enviar', array('as' => 'oportunidades.enviar', 'uses' => 'OportunidadesController@enviar'));
Route::get('cases', array('as' => 'cases', 'uses' => 'CasesController@index'));
Route::get('cases/cases', array('as' => 'cases', 'uses' => 'CasesController@index'));
Route::get('cases/depoimentos', array('as' => 'cases.depoimentos', 'uses' => 'DepoimentosController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('contato/enviar', array('as' => 'contato.enviar', 'uses' => 'ContatoController@enviar'));

/* LOCALIZAÇÃO */
Route::get('idioma/{sigla_idioma?}', function($sigla_idioma){
	if($sigla_idioma == 'pt' || $sigla_idioma == 'en')
		Session::put('locale', $sigla_idioma);

	return Redirect::back();
});

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
	Route::get('downloadCV/{id}', function($id){

		$candidato = Candidato::find($id);

		return Response::download(base_path('curriculos/'.$candidato->curriculo));
	});

	Route::post('candidatos/buscarNome', array('as' => 'painel.buscacandidato.nome', 'uses' => 'Painel\CandidatosController@buscarNome'));
	Route::post('candidatos/buscarData', array('as' => 'painel.buscacandidato.data', 'uses' => 'Painel\CandidatosController@buscarData'));

    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banners', 'Painel\BannersController');
	Route::resource('quemsomos', 'Painel\QuemSomosController');
	Route::resource('politica-de-privacidade', 'Painel\PrivacidadeController');
	Route::resource('equipe', 'Painel\EquipeController');
	Route::resource('diferenciais', 'Painel\DiferenciaisController');
	Route::resource('cursos', 'Painel\CursosController');
	// Route::resource('oportunidades', 'Painel\OportunidadesController');
	// Route::resource('oportunidadesarquivadas', 'Painel\OportunidadesArquivadasController');
	Route::resource('candidatos', 'Painel\CandidatosController');
	Route::resource('cases', 'Painel\CasesController');
	Route::resource('depoimentos', 'Painel\DepoimentosController');
	Route::resource('contato', 'Painel\ContatoController');
	Route::resource('solucoes', 'Painel\SolucoesController');
//NOVASROTASDOPAINEL//
});

laravel/app/models/Privacidade.php
<?php

class Privacidade extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'novosite_privacidade';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

}

laravel/app/controllers/PrivacidadeController.php
<?php

use \Privacidade, \Equipe;

class PrivacidadeController extends BaseController {

	protected $layout = 'frontend.templates.index';

	public function index()
	{
		$this->layout->content = View::make('frontend.privacidade.index')->with('texto', Privacidade::first());
	}

}

laravel/app/controllers/painel/PrivacidadeController.php
<?php

namespace Painel;

use View, Input, Str, Session, Redirect, Hash, Thumb, File, Privacidade;

class PrivacidadeController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = '1';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.privacidade.index')->with('registros', Privacidade::all())->with('limiteInsercao', $this->limiteInsercao);		
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.privacidade.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Privacidade;

		$object->texto_pt = Input::get('texto_pt');
		$object->texto_en = Input::get('texto_en');


		if($this->limiteInsercao && sizeof( Privacidade::all() ) >= $this->limiteInsercao)
			return Redirect::back()->withErrors(array('Número máximo de Registros atingido!'));

		
		try {

			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Texto criado com sucesso.');
			return Redirect::route('painel.politica-de-privacidade.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Texto!'));	

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.privacidade.edit')->with('registro', Privacidade::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Privacidade::find($id);

		$object->texto_pt = Input::get('texto_pt');
		$object->texto_en = Input::get('texto_en');


		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Texto alterado com sucesso.');
			return Redirect::route('painel.politica-de-privacidade.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Texto!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Privacidade::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Texto removido com sucesso.');

		return Redirect::route('painel.politica-de-privacidade.index');
	}

}

laravel/app/views/backend/privacidade/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Texto
        </h2>  

		{{ Form::open( array('route' => array('painel.politica-de-privacidade.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	


				<div class="form-group">
					<label for="inputTextoPT">Texto em Português</label>
					<textarea name="texto_pt" class="form-control" id="inputTextoPT" >{{$registro->texto_pt }}</textarea>
				</div>
				<div class="form-group">
					<label for="inputTextoEN">Texto em Inglês</label>
					<textarea name="texto_en" class="form-control" id="inputTextoEN" >{{$registro->texto_en }}</textarea>
				</div>

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.politica-de-privacidade.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/privacidade/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Texto
        </h2>  

		<form action="{{URL::route('painel.politica-de-privacidade.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif


				<div class="form-group">
					<label for="inputTextoPT">TextoPT</label>
					<textarea name="texto_pt" class="form-control" id="inputTextoPT" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['texto_pt'] }} @endif</textarea>
				</div>	
				<div class="form-group">
					<label for="inputTextoEN">TextoEN</label>
					<textarea name="texto_en" class="form-control" id="inputTextoEN" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['texto_en'] }} @endif</textarea>
				</div>	

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.politica-de-privacidade.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/privacidade/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Política de Privacidade
    </h2>

    <table class='table table-striped table-bordered table-hover'>

        <thead>
            <tr>
                <th>Título</th>
                <th>Texto</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td>Política de Privacidade</td>
                <td>
                    Português : <br>{{ Str::words(strip_tags($registro->texto_pt), 30) }}
                    <hr>
				    Inglês : <br>{{ Str::words(strip_tags($registro->texto_en), 30) }}
                </td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.politica-de-privacidade.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    
</div>

@stop