laravel/app/routes.php
<?php

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('/home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('empresa', array('as' => 'quemsomos', 'uses' => 'QuemsomosController@index'));
Route::get('empresa/quemsomos', array('as' => 'quemsomos', 'uses' => 'QuemsomosController@index'));
Route::get('politica-de-privacidade', array('as' => 'privacidade', 'uses' => 'PrivacidadeController@index'));
Route::get('empresa/diferenciais', array('as' => 'diferenciais', 'uses' => 'DiferenciaisController@index'));
Route::get('solucoes/{slug?}', array('as' => 'solucoes', 'uses' => 'SolucoesController@index'));
// Route::get('oportunidades', array('as' => 'oportunidades', 'uses' => 'OportunidadesController@index'));
// Route::get('oportunidades/detalhe/{slug?}', array('as' => 'oportunidades', 'uses' => 'OportunidadesController@detalhe'));
// Route::post('oportunidades/enviar', array('as' => 'oportunidades.enviar', 'uses' => 'OportunidadesController@enviar'));
Route::get('cases', array('as' => 'cases', 'uses' => 'CasesController@index'));
Route::get('cases/cases', array('as' => 'cases', 'uses' => 'CasesController@index'));
Route::get('cases/depoimentos', array('as' => 'cases.depoimentos', 'uses' => 'DepoimentosController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('contato/enviar', array('as' => 'contato.enviar', 'uses' => 'ContatoController@enviar'));

/* LOCALIZAÇÃO */
Route::get('idioma/{sigla_idioma?}', function($sigla_idioma){
	if($sigla_idioma == 'pt' || $sigla_idioma == 'en')
		Session::put('locale', $sigla_idioma);

	return Redirect::back();
});

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
	Route::get('downloadCV/{id}', function($id){

		$candidato = Candidato::find($id);

		return Response::download(base_path('curriculos/'.$candidato->curriculo));
	});

	Route::post('candidatos/buscarNome', array('as' => 'painel.buscacandidato.nome', 'uses' => 'Painel\CandidatosController@buscarNome'));
	Route::post('candidatos/buscarData', array('as' => 'painel.buscacandidato.data', 'uses' => 'Painel\CandidatosController@buscarData'));

    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banners', 'Painel\BannersController');
	Route::resource('quemsomos', 'Painel\QuemSomosController');
	Route::resource('politica-de-privacidade', 'Painel\PrivacidadeController');
	Route::resource('equipe', 'Painel\EquipeController');
	Route::resource('diferenciais', 'Painel\DiferenciaisController');
	Route::resource('cursos', 'Painel\CursosController');
	// Route::resource('oportunidades', 'Painel\OportunidadesController');
	// Route::resource('oportunidadesarquivadas', 'Painel\OportunidadesArquivadasController');
	Route::resource('candidatos', 'Painel\CandidatosController');
	Route::resource('cases', 'Painel\CasesController');
	Route::resource('depoimentos', 'Painel\DepoimentosController');
	Route::resource('contato', 'Painel\ContatoController');
	Route::resource('solucoes', 'Painel\SolucoesController');
//NOVASROTASDOPAINEL//
});

laravel/app/models/Depoimento.php
<?php

class Depoimento extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'novosite_depoimentos';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

    public function scopeOrdenado($query)
    {
    	return $query->orderBy('empresa', 'asc')->get();
    }
}

laravel/app/controllers/DepoimentosController.php
<?php

use \Depoimento;

class DepoimentosController extends BaseController {

	protected $layout = 'frontend.templates.index';

	public function index()
	{
		$this->layout->content = View::make('frontend.depoimentos.index')->with('depoimentos', Depoimento::ordenado());
	}

}

laravel/app/controllers/painel/DepoimentosController.php
<?php

namespace Painel;

use View, Input, Str, Session, Redirect, Hash, Thumb, File, Depoimento;

class DepoimentosController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.depoimentos.index')->with('registros', Depoimento::ordenado());		
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.depoimentos.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Depoimento;

		$object->empresa = Input::get('empresa');
		$object->titulo_pt = Input::get('titulo_pt');
		$object->titulo_en = Input::get('titulo_en');
		$object->texto_pt = Input::get('texto_pt');
		$object->texto_en = Input::get('texto_en');
		$object->autoria_pt = Input::get('autoria_pt');
		$object->autoria_en = Input::get('autoria_en');
		
		$imagem = Thumb::make('imagem', 290, null, 'depoimentos/');
		if($imagem) $object->imagem = $imagem;

		try {

			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Depoimento criado com sucesso.');
			return Redirect::route('painel.depoimentos.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Depoimento!'));	

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.depoimentos.edit')->with('registro', Depoimento::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Depoimento::find($id);

		$object->empresa = Input::get('empresa');
		$object->titulo_pt = Input::get('titulo_pt');
		$object->titulo_en = Input::get('titulo_en');
		$object->texto_pt = Input::get('texto_pt');
		$object->texto_en = Input::get('texto_en');
		$object->autoria_pt = Input::get('autoria_pt');
		$object->autoria_en = Input::get('autoria_en');

		$imagem = Thumb::make('imagem', 290, null, 'depoimentos/');
		if($imagem) $object->imagem = $imagem;

		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Depoimento alterado com sucesso.');
			return Redirect::route('painel.depoimentos.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Depoimento!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Depoimento::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Depoimento removido com sucesso.');

		return Redirect::route('painel.depoimentos.index');
	}

}

laravel/app/views/backend/depoimentos/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Depoimento
        </h2>  

		{{ Form::open( array('route' => array('painel.depoimentos.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

				<div class="form-group">
					<label for="inputEmpresa">Empresa</label>
					<input type="text" class="form-control" id="inputEmpresa" name="empresa" value="{{$registro->empresa}}" required>
				</div>

				<div class="form-group">
					<label for="inputTítulo">Título em Português</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo_pt" value="{{$registro->titulo_pt}}" required>
				</div>
				
				<div class="form-group">
					<label for="inputTítulo">Título em Inglês</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo_en" value="{{$registro->titulo_en}}" required>
				</div>
				
				<div class="form-group">
					<label for="inputTexto">Texto em Português</label>
					<textarea name="texto_pt" class="form-control" id="inputTexto" >{{$registro->texto_pt }}</textarea>
				</div>
				
				<div class="form-group">
					<label for="inputTexto">Texto em Inglês</label>
					<textarea name="texto_en" class="form-control" id="inputTexto" >{{$registro->texto_en }}</textarea>
				</div>
				
				<div class="form-group">
					<label for="inputAutoria">Autoria em Português</label>
					<input type="text" class="form-control" id="inputAutoria" name="autoria_pt" value="{{$registro->autoria_pt}}" >
				</div>
				
				<div class="form-group">
					<label for="inputAutoria">Autoria em Inglês</label>
					<input type="text" class="form-control" id="inputAutoria" name="autoria_en" value="{{$registro->autoria_en}}" >
				</div>
				
				<div class="form-group">
					@if($registro->imagem)
						Imagem Atual<br>
						<img src="assets/images/depoimentos/{{$registro->imagem}}"><br>
					@endif
					<label for="inputImagem">Trocar Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem">
				</div>
				

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.depoimentos.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/depoimentos/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Depoimento
        </h2>  

		<form action="{{URL::route('painel.depoimentos.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif

				<div class="form-group">
					<label for="inputEmpresa">Empresa</label>
					<input type="text" class="form-control" id="inputEmpresa" name="empresa" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['empresa'] }}" @endif required>
				</div>

				<div class="form-group">
					<label for="inputTítulo">Título em Português</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo_pt" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['titulo_pt'] }}" @endif required>
				</div>
				
				<div class="form-group">
					<label for="inputTítulo">Título em Inglês</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo_en" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['titulo_en'] }}" @endif required>
				</div>
				
				<div class="form-group">
					<label for="inputTexto">Texto em Português</label>
					<textarea name="texto_pt" class="form-control" id="inputTexto" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['texto_pt'] }} @endif</textarea>
				</div>	
				
				<div class="form-group">
					<label for="inputTexto">Texto em Inglês</label>
					<textarea name="texto_en" class="form-control" id="inputTexto" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['texto_en'] }} @endif</textarea>
				</div>	
				
				<div class="form-group">
					<label for="inputAutoria">Autoria em Português</label>
					<input type="text" class="form-control" id="inputAutoria" name="autoria_pt" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['autoria_pt'] }}" @endif >
				</div>
				
				<div class="form-group">
					<label for="inputAutoria">Autoria em Inglês</label>
					<input type="text" class="form-control" id="inputAutoria" name="autoria_en" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['autoria_en'] }}" @endif >
				</div>
				
				<div class="form-group">
					<label for="inputImagem">Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem" required>
				</div>
				

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.depoimentos.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/depoimentos/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Depoimentos <a href='{{ URL::route('painel.depoimentos.create') }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Depoimento</a>
    </h2>

    <table class='table table-striped table-bordered table-hover' data-tabela='depoimentos'>

        <thead>
            <tr>
                <th>Empresa</th>
                <th>Título</th>
				<th>Texto</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td>{{ $registro->empresa }}</td>
                <td>{{ $registro->titulo_pt }}</td>
				<td>
                    Português : <br>{{ Str::words(strip_tags($registro->texto_pt), 15) }}
                    <hr>
				    Inglês : <br>{{ Str::words(strip_tags($registro->texto_en), 15) }}
                </td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.depoimentos.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
					{{ Form::open(array('route' => array('painel.depoimentos.destroy', $registro->id), 'method' => 'delete')) }}
						<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
					{{ Form::close() }}                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    
</div>

@stop